/// The evidence bridge: turn a manifest + proof report + TRX into SDD `evidence.yml` rows, enforcing
/// the satisfaction rule (only an `InputDriven` proof whose test passed is `pass ∧ ¬synthetic`; a
/// `Synthetic` proof is disclosed `synthetic: true`; anything else fails closed).
module FS.GG.Playtest.Evidence

open FS.GG.Playtest.Manifest
open FS.GG.Playtest.Proofs
open FS.GG.Playtest.Trx

/// One emitted evidence row for a gameplay-FR.
type Row =
    { Id: string
      RequirementRefs: string list
      CoversAc: int list
      Result: string
      Synthetic: bool
      Note: string }

/// Classify one GP against the run and proof report — the satisfaction rule, made mechanical.
let rowFor (run: TrxRun) (proofs: Map<string, Provenance>) (evId: string) (fr: GameplayFr) : Row =
    let contains (id: string) (name: string) = name.Contains id
    let testedGreen = run.PassedTestNames |> List.exists (contains fr.Id)
    let testExists = run.AllTestNames |> List.exists (contains fr.Id)
    let provenance = proofs |> Map.tryFind fr.Id |> Option.defaultValue Missing

    let result, synthetic, note =
        match provenance with
        | Synthetic -> "pass", true, "synthetic proof — disclosed, does not satisfy the gameplay obligation"
        | InputDriven when testedGreen -> "pass", false, "InputDriven proof and a passing test — satisfies"
        | InputDriven when testExists -> "fail", false, "InputDriven proof but its test did not pass"
        | InputDriven -> "missing", false, "InputDriven proof declared but no matching passing test in the TRX"
        | Missing -> "missing", false, "no proof entry for this gameplay-FR"

    { Id = evId
      RequirementRefs = [ fr.Id ]
      CoversAc = fr.CoversAc
      Result = result
      Synthetic = synthetic
      Note = note }

/// Every emitted row for the manifest, in manifest order (EV ids assigned sequentially).
let rows (run: TrxRun) (proofs: Map<string, Provenance>) (manifest: GameplayFr list) : Row list =
    manifest |> List.mapi (fun i fr -> rowFor run proofs (sprintf "EV%03d" (i + 1)) fr)

/// Render the rows as a valid SDD `evidence.yml` document with the TRX `observedRun` receipt.
let render (trxPath: string) (run: TrxRun) (rows: Row list) : string =
    let sb = System.Text.StringBuilder()
    let line (s: string) = sb.AppendLine s |> ignore
    line "schemaVersion: 1"
    line "# Generated by fsgg-playtest emit-evidence — the tool enforces the satisfaction rule."
    line "evidence:"

    for r in rows do
        let acRefs = r.CoversAc |> List.map (sprintf "AC-%03d") |> String.concat ", "
        line (sprintf "  - id: %s" r.Id)
        line "    kind: verification"
        line "    subject:"
        line "      type: requirement"
        line (sprintf "      id: %s" (List.head r.RequirementRefs))
        line (sprintf "    requirementRefs: [%s]" (String.concat ", " r.RequirementRefs))
        line (sprintf "    acceptanceScenarioRefs: [%s]" acRefs)
        line (sprintf "    result: %s" r.Result)
        line (sprintf "    synthetic: %b" r.Synthetic)
        line "    observedRun:"
        line (sprintf "      source: %s" trxPath)
        line (sprintf "      digest: \"sha256:%s\"" run.Digest)
        line (sprintf "      outcome: %s" (if run.Failed = 0 then "passed" else "failed"))
        line (sprintf "      passed: %d" run.Passed)
        line (sprintf "      failed: %d" run.Failed)
        line (sprintf "      skipped: %d" run.Skipped)
        line (sprintf "    notes: [\"%s\"]" r.Note)

    sb.ToString()
