/// The evidence bridge: turn a manifest + proof report + TRX into SDD `evidence.yml` rows, enforcing
/// the satisfaction rule (only an `InputDriven` proof whose test passed is `pass ∧ ¬synthetic`; a
/// `Synthetic` proof is disclosed `synthetic: true`; anything else fails closed).
module FS.GG.Playtest.Evidence

open System.Text.RegularExpressions
open FS.GG.Playtest.JourneyReceiptExport
open FS.GG.Playtest.Manifest
open FS.GG.Playtest.Proofs
open FS.GG.Playtest.Trx

/// One emitted evidence row for a gameplay-FR.
type Row =
    { Id: string
      RequirementRefs: string list
      CoversAc: int list
      Result: string
      Synthetic: bool
      Note: string }

/// Classify one GP against the run and proof report — the satisfaction rule, made mechanical.
let rowFor (run: TrxRun) (proofs: Map<string, Provenance>) (evId: string) (fr: GameplayFr) : Row =
    // Match the GP id as a whole token, not a substring — otherwise "GP-1" spuriously matches a test
    // named "...GP-10...". Boundaries: the id must not be flanked by another alphanumeric.
    let idPattern = "(?<![0-9A-Za-z])" + Regex.Escape fr.Id + "(?![0-9A-Za-z])"
    let mentions (name: string) = Regex.IsMatch(name, idPattern)
    let testedGreen = run.PassedTestNames |> List.exists mentions
    let testExists = run.AllTestNames |> List.exists mentions
    let provenance = proofs |> Map.tryFind fr.Id |> Option.defaultValue Missing

    let result, synthetic, note =
        match provenance with
        | Synthetic -> "pass", true, "synthetic proof — disclosed, does not satisfy the gameplay obligation"
        | ProductionJourney when testedGreen -> "pass", false, "runner-issued production journey receipt and a passing bound test — satisfies"
        | ProductionJourney when testExists -> "fail", false, "production journey receipt exists but its bound test did not pass"
        | ProductionJourney -> "missing", false, "production journey receipt has no matching passing test in the TRX"
        | InputDriven when fr.RequiredEvidence = EvidenceLevel.ProductionJourney ->
            "missing", false, "simulation/component input proof cannot satisfy required production-journey coverage"
        | InputDriven when testedGreen -> "pass", false, "InputDriven proof and a passing test — satisfies"
        | InputDriven when testExists -> "fail", false, "InputDriven proof but its test did not pass"
        | InputDriven -> "missing", false, "InputDriven proof declared but no matching passing test in the TRX"
        | Missing -> "missing", false, "no proof entry for this gameplay-FR"

    { Id = evId
      RequirementRefs = [ fr.Id ]
      CoversAc = fr.CoversAc
      Result = result
      Synthetic = synthetic
      Note = note }

/// Classify production rows from the generated same-execution journey report, never from the
/// caller-supplied general TRX. Other evidence levels retain their existing TRX classification.
let rowForWithJourneyReceipts
    (run: TrxRun)
    (journeys: Map<string, BoundReceipt>)
    (proofs: Map<string, Provenance>)
    (evId: string)
    (fr: GameplayFr)
    : Row =
    match Map.tryFind fr.Id proofs with
    | Some ProductionJourney ->
        let result, note =
            if Map.containsKey fr.Id journeys then
                "pass", "runner-issued production journey receipt and generated same-execution JUnit — satisfies"
            else
                "missing", "production journey receipt has no generated same-execution JUnit binding"

        { Id = evId
          RequirementRefs = [ fr.Id ]
          CoversAc = fr.CoversAc
          Result = result
          Synthetic = false
          Note = note }
    | _ -> rowFor run proofs evId fr

/// Every emitted row for the manifest, in manifest order (EV ids assigned sequentially).
let rows (run: TrxRun) (proofs: Map<string, Provenance>) (manifest: GameplayFr list) : Row list =
    manifest |> List.mapi (fun i fr -> rowFor run proofs (sprintf "EV%03d" (i + 1)) fr)

let rowsWithJourneyReceipts
    (run: TrxRun)
    (journeys: Map<string, BoundReceipt>)
    (proofs: Map<string, Provenance>)
    (manifest: GameplayFr list)
    : Row list =
    manifest
    |> List.mapi (fun i fr ->
        rowForWithJourneyReceipts run journeys proofs (sprintf "EV%03d" (i + 1)) fr)

/// Render the rows as a valid SDD `evidence.yml` document with the TRX `observedRun` receipt and
/// schema-v1 typed journey receipts for production-journey rows.
let renderWithJourneyReceipts
    (trxPath: string)
    (run: TrxRun)
    (journeys: Map<string, BoundReceipt>)
    (rows: Row list)
    : string =
    let sb = System.Text.StringBuilder()
    let line (s: string) = sb.AppendLine s |> ignore
    line "schemaVersion: 1"
    line "# Generated by fsgg-playtest emit-evidence — the tool enforces the satisfaction rule."
    line "evidence:"

    for r in rows do
        let acRefs = r.CoversAc |> List.map (sprintf "AC-%03d") |> String.concat ", "
        line (sprintf "  - id: %s" r.Id)
        line "    kind: verification"
        line "    subject:"
        line "      type: requirement"
        line (sprintf "      id: %s" (List.head r.RequirementRefs))
        line (sprintf "    requirementRefs: [%s]" (String.concat ", " r.RequirementRefs))
        line (sprintf "    acceptanceScenarioRefs: [%s]" acRefs)
        line (sprintf "    result: %s" r.Result)
        line (sprintf "    synthetic: %b" r.Synthetic)

        let journey =
            match r.RequirementRefs with
            | [ testId ] -> Map.tryFind testId journeys
            | _ -> None

        line "    observedRun:"

        match journey with
        | Some bound ->
            line (sprintf "      source: %s" bound.ReportSource)
            line (sprintf "      digest: \"sha256:%s\"" bound.ReportDigest)
            line "      outcome: passed"
            line (sprintf "      passed: %d" bound.ReportPassed)
            line "      failed: 0"
            line "      skipped: 0"
        | None ->
            line (sprintf "      source: %s" trxPath)
            line (sprintf "      digest: \"sha256:%s\"" run.Digest)
            line (sprintf "      outcome: %s" (if run.Failed = 0 then "passed" else "failed"))
            line (sprintf "      passed: %d" run.Passed)
            line (sprintf "      failed: %d" run.Failed)
            line (sprintf "      skipped: %d" run.Skipped)

        match journey with
        | Some journey ->
            line "    journeyReceipt:"
            JourneyReceiptExport.renderYaml "      " journey |> List.iter line
        | None -> ()

        line (sprintf "    notes: [\"%s\"]" r.Note)

    sb.ToString()

/// Compatibility renderer for evidence sets without production-journey receipts.
let render (trxPath: string) (run: TrxRun) (rows: Row list) : string =
    renderWithJourneyReceipts trxPath run Map.empty rows
