<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="LinuxDescriptors.fs" />
    <Compile Include="ReadOnlySource.fs" />
    <ProjectReference Include="../FS.GG.Game.SkillStaging.Policy/FS.GG.Game.SkillStaging.Policy.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>SkillStaging.Source.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
