// Generated by scripts/generate-fable-lockstep-cases.py from fixtures/v1/cases.json.
// Do not edit this file directly.
namespace FS.GG.Game.Core.LockstepFixtures

open FS.GG.Game.Core

type Fixture =
    | CellOrder of caseId: int * cells: Cell list
    | EdgeBetween of caseId: int * a: Cell * b: Cell
    | LineOfSight of caseId: int * mode: LineMode * a: Cell * b: Cell * blocked: Cell list
    | Astar of
        caseId: int *
        neighbourhood: Neighbourhood *
        maxVisited: int *
        start: Cell *
        goal: Cell *
        bounds: (int * int * int * int) *
        blocked: Cell list

[<RequireQualifiedAccess>]
module GeneratedCases =

    let private cell col row : Cell = { Col = col; Row = row }

    let all : Fixture list =
        [ CellOrder (1001, [ cell 2 -1; cell -3 4; cell 2 -2; cell System.Int32.MinValue System.Int32.MaxValue; cell System.Int32.MaxValue System.Int32.MinValue ])
          CellOrder (1002, [ cell 0 0; cell 0 -1; cell -1 0; cell 0 0; cell 1 0 ])
          EdgeBetween (2001, cell -4 9, cell -3 9)
          EdgeBetween (2002, cell -3 9, cell -4 9)
          EdgeBetween (2003, cell -4 9, cell -2 9)
          EdgeBetween (2004, cell System.Int32.MinValue 0, cell -2147483647 0)
          EdgeBetween (2005, cell System.Int32.MaxValue 0, cell System.Int32.MinValue 0)
          LineOfSight (3001, Supercover, cell 0 0, cell 2 1, [ cell 1 0 ])
          LineOfSight (3002, Supercover, cell 2 1, cell 0 0, [ cell 1 0 ])
          LineOfSight (3003, Thin, cell -2 -2, cell 2 2, [  ])
          LineOfSight (3004, Thin, cell -2 -2, cell 2 2, [ cell 0 0; cell 1 1 ])
          Astar (4001, FourWay, 16, cell 0 0, cell 2 0, (0, 2, 0, 1), [ cell 1 0 ])
          Astar (4002, FourWay, 32, cell 0 0, cell 2 2, (0, 2, 0, 2), [ cell 1 1 ])
          Astar (4003, FourWay, 1, cell 0 0, cell 2 0, (0, 2, 0, 0), [  ])
          Astar (4004, EightWay, 16, cell 1 1, cell 1 1, (0, 2, 0, 2), [ cell 2 2; cell 0 0 ])
          Astar (4005, FourWay, 32, cell 0 0, cell 2 0, (0, 2, 0, 1), [ cell 2 1; cell 1 0; cell 1 1 ]) ]
