#!/usr/bin/env bash
#
# Fail on an `.fsi` doc comment that names an FS.GG.Game symbol the package does not export
# (FS.GG.Game#385).
#
# Nothing in this repo ever checked doc PROSE against our own exported surface. A doc comment could
# name any symbol at all — private, renamed, or invented — and every gate here stayed green.
#
# That is how FS.GG.Game#378 happened. #340 added a cross-reference to `Physics.circleCircleManifold`,
# which is `let private` and therefore absent from the published surface. It sat wrong for weeks.
#
# FS.GG.Rendering found it, not us. Their doc-vs-pin rule (their #589/#550) asserts that no shipped
# template doc names an `FS.GG.*` symbol absent from the pinned package, and it went red the moment
# their generated mirror imported our prose (their #752). So the defect was detected ONE REPO
# DOWNSTREAM — after we pack, after they pin, by someone with none of the context, long after the
# author who could have fixed it in seconds was gone. This gate moves that detection to authoring
# time. It does not duplicate theirs: theirs guards THEIR templates against THEIR pin and fires only
# for symbols that reach a template; ours guards the source. Same rule, different subject, and the
# earlier one is the one that saves the work.
#
# THE ORACLE IS ALREADY CHECKED IN, so this needs no build and no reflection.
# `readiness/surface-baselines/members/<pkg>.txt` enumerates every exported member and
# `readiness/surface-baselines/<pkg>.txt` every exported type; both are regenerated by
# scripts/refresh-surface-baselines.fsx and guarded against drift by gate.yml's
# `surface-baseline-drift` job (#236). A symbol absent from those files is absent from the package.
#
# THE FAILURE THAT MATTERS IS NOT THIS SCRIPT GOING RED. It is this script matching NOTHING — a
# renamed baseline, a re-shaped member line, a doc convention that drifts off backticks — and
# reporting that in GREEN, which is indistinguishable from "every doc reference resolves" (the
# FS-GG/.github#266 shape, and the same reason check-pin-coherence.sh asserts its subject exists
# before it asserts it is clean). So this script asserts its SUBJECT before its VERDICT: absent
# baselines are a red, absent `.fsi` files are a red, and finding fewer than MIN_REFS resolvable
# references across the tree is a red, because a coverage claim over nothing is a claim about nothing.
#
# WHAT IS IN SCOPE, and why each boundary is where it is:
#
#   `.fsi` ONLY, never `.fs`. The `.fsi` is the public contract and the thing mirrored downstream.
#   The `.fs` is not, and it deliberately names private symbols: `Geometry.fs` documents its own
#   `circleContact` by contrasting it with the private `Physics.circleCircleManifold` and pointing at
#   that symbol's comment. That is correct for a maintainer reading the implementation, and flagging
#   it would be a false positive that teaches readers to ignore this gate.
#
#   QUALIFIED references only. `Module.symbol` inside backticks. A bare `polygonManifold`
#   (Physics.fsi:191, meaning `Geometry.polygonManifold`) carries no module to resolve against and is
#   out of scope for this cut — resolving it would mean guessing which module was meant.
#
#   ONE LINE per reference. A code span that WRAPS across two `///` lines is not read, so a reference
#   inside one is invisible here — a FALSE NEGATIVE, and a real one: twelve spans in the tree wrap
#   today (`Ai.fsi:51` carries `Ai.view` inside one). It is a gap, not a lie: this gate reports the
#   references it READ and claims nothing about the ones it did not, which is why the green line prints
#   a count. It fails SAFE in the other direction too — the mispaired backticks a wrap leaves behind
#   yield no false positive, because a fragment that is not a dotted identifier does not match, and
#   anything that survives that still has to pass the root and val filters. Reading `///` blocks rather
#   than lines would close it, at the cost of attributing a finding to the right line; worth doing,
#   not this change. test-check-fsi-doc-surface.sh pins the boundary in both directions so it stays a
#   decision rather than becoming an accident.
#
#   OUR ROOTS only. The first segment must name something our own baseline exports, so `Int32.MaxValue`,
#   `Map.tryFind`, `FS.GG.UI.Scene.Rect` and a field access like `damage.Base` are skipped rather than
#   reported as symbols we fail to export — we have no opinion on another package's surface. The roots
#   are DERIVED from the baseline, not hardcoded, so a new module is covered the day it ships.
#
#   VALS only, not types or DU cases. F# spells vals camelCase and types, union cases and record
#   fields PascalCase, so the last segment's case discriminates them exactly. Vals are restricted to
#   what the baseline can actually answer, and TYPES ARE NOT: the member baseline enumerates a
#   DU case only when it carries fields (`ProjectileStep+Flew` is listed; the nullary
#   `Source+Declared` is not, only `Source+Tags`), so a case-name rule would report correct prose —
#   `Source.Declared`, `Command.Fire` — as unresolved. Type references likewise: `Loop.StepState`
#   correctly names the type the `Loop` module returns, but the baseline emits it top-level as
#   `StepState`, so a naive type rule flags it. Widening to types means teaching the resolver those
#   two shapes; it is worth doing and it is not this change. Until then this gate says nothing about
#   them rather than saying something wrong.
#
#   usage: scripts/check-fsi-doc-surface.sh [baseline-dir] [src-dir]
#
set -uo pipefail

BASELINE_DIR="${1:-readiness/surface-baselines}"
SRC_DIR="${2:-src}"

# ZERO-MATCH GUARD with a floor. The tree carries ~30 resolvable references today; a collapse toward
# zero means the doc convention or the extraction rotted, not that the docs got cleaner. This is the
# number that turns "I matched nothing" from a pass into a red.
MIN_REFS="${MIN_REFS:-10}"

rc=0

# ---- subject: the baselines -------------------------------------------------------------------

if [[ ! -d $BASELINE_DIR/members ]]; then
  echo "::error::check-fsi-doc-surface: $BASELINE_DIR/members not found. The member baseline is the ORACLE for this gate — a missing oracle is a finding, not a pass. Run: dotnet fsi scripts/refresh-surface-baselines.fsx"
  echo "check-fsi-doc-surface: $BASELINE_DIR/members not found" >&2
  exit 1
fi

mapfile -t member_files < <(find "$BASELINE_DIR/members" -name '*.txt' -type f | sort)
if (( ${#member_files[@]} == 0 )); then
  echo "::error::check-fsi-doc-surface: no member baselines under $BASELINE_DIR/members. The oracle is empty, so every reference would 'resolve' against nothing and this gate would be green over a surface it never read."
  echo "check-fsi-doc-surface: no member baselines under $BASELINE_DIR/members" >&2
  exit 1
fi

# ---- build the resolvable-name set and the root set -------------------------------------------
#
# A member line is `<fully.qualified.name><generics>(<args>) : <return>` or `<name> : <type> [get]`.
# Strip everything from the first `<`, `(` or ` :` — what remains is the name we resolve against.
# A type line is already a bare name; `+` marks nesting and normalises to `.`, and a `` `N `` arity
# suffix is not part of the source-level name.
names_file=$(mktemp)
roots_file=$(mktemp)
trap 'rm -f "$names_file" "$roots_file"' EXIT

{
  cat "${member_files[@]}"
  find "$BASELINE_DIR" -maxdepth 1 -name '*.txt' -type f -exec cat {} +
} | sed -E 's/[<(].*//; s/ :.*//; s/`[0-9]+//g; s/\+/./g; s/[[:space:]]+$//' |
  grep -E '^[A-Za-z_]' | sort -u > "$names_file"

if [[ ! -s $names_file ]]; then
  echo "::error::check-fsi-doc-surface: parsed 0 names out of $BASELINE_DIR. The baseline files exist but nothing matched the expected member/type line shape — the generator's format changed and this gate's parse rotted. It will NOT report that as green."
  echo "check-fsi-doc-surface: parsed 0 names from the baselines (format drift)" >&2
  exit 1
fi

# The namespaces we own, derived from the baseline FILENAMES (`members/FS.GG.Game.Core.txt` →
# `FS.GG.Game.Core`), so a new package is covered the day its baseline lands.
mapfile -t namespaces < <(basename -a "${member_files[@]}" | sed -E 's/\.txt$//' | sort -u)

# The roots we own: the first segment under each namespace. Derived, never hardcoded.
for ns in "${namespaces[@]}"; do
  sed -nE "s/^${ns//./\\.}\.([A-Za-z_][A-Za-z0-9_]*).*/\1/p" "$names_file"
done | sort -u > "$roots_file"

if [[ ! -s $roots_file ]]; then
  echo "::error::check-fsi-doc-surface: derived 0 module roots from $BASELINE_DIR. Every reference would be skipped as 'not ours' and this gate would pass without resolving a single symbol."
  echo "check-fsi-doc-surface: derived 0 roots (namespace shape changed?)" >&2
  exit 1
fi

# ---- subject: the .fsi files ------------------------------------------------------------------

mapfile -t fsi_files < <(find "$SRC_DIR" -name '*.fsi' -type f | sort)
if (( ${#fsi_files[@]} == 0 )); then
  echo "::error::check-fsi-doc-surface: no .fsi files under $SRC_DIR. The signature files are the SUBJECT of this gate — if they moved, this gate is reading nothing and must say so rather than pass."
  echo "check-fsi-doc-surface: no .fsi files under $SRC_DIR" >&2
  exit 1
fi

# ---- extract, filter, resolve -----------------------------------------------------------------

considered=0
unresolved=0

for f in "${fsi_files[@]}"; do
  # `///` doc lines only — the published contract. Emit `line<TAB>ref` for each backticked,
  # dot-qualified reference on them.
  while IFS=$'\t' read -r ln ref; do
    [[ -n $ref ]] || continue

    # Strip our own namespace, so `FS.GG.Game.Core.Grids.cellRect` and `Grids.cellRect` resolve alike.
    short=$ref
    for ns in "${namespaces[@]}"; do
      short=${short#"$ns".}
    done

    root=${short%%.*}
    last=${short##*.}

    # Ours? A root the baseline does not export is another package's, or a local value — not our claim.
    grep -qxF "$root" "$roots_file" || continue

    # Val-shaped? camelCase last segment. PascalCase is a type, union case or record field — see the
    # scope note in the header for why those are out of this cut.
    [[ $last =~ ^[a-z] ]] || continue

    considered=$((considered + 1))

    resolved=0
    for ns in "${namespaces[@]}"; do
      if grep -qxF "$ns.$short" "$names_file"; then
        resolved=1
        break
      fi
    done

    if (( resolved == 0 )); then
      echo "::error file=$f,line=$ln::check-fsi-doc-surface: this doc comment names \`$ref\`, which the package does NOT export. A published doc may only name a published symbol: readers cannot call this, and FS.GG.Rendering's doc-vs-pin rule goes red when it mirrors this prose. Name the exported symbol instead, or drop the reference. (If the symbol SHOULD be exported, export it and re-run scripts/refresh-surface-baselines.fsx.)"
      echo "check-fsi-doc-surface: $f:$ln — UNRESOLVED \`$ref\` (not in the exported surface)" >&2
      unresolved=$((unresolved + 1))
      rc=1
    fi
  done < <(
    grep -nE '^[[:space:]]*///' "$f" |
      sed -E 's/^([0-9]+):/\1\t/' |
      awk -F'\t' '{
        line = $1
        rest = $2
        while (match(rest, /`[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)+`/)) {
          ref = substr(rest, RSTART + 1, RLENGTH - 2)
          print line "\t" ref
          rest = substr(rest, RSTART + RLENGTH)
        }
      }'
  )
done

# ---- zero-match guard -------------------------------------------------------------------------

if (( considered < MIN_REFS )); then
  echo "::error::check-fsi-doc-surface: resolved only $considered reference(s) across ${#fsi_files[@]} .fsi file(s), expected at least $MIN_REFS. This gate will NOT report that as green — a coverage claim over nothing is a claim about nothing. Either the backticked \`Module.symbol\` doc convention changed, or the extraction rotted. (Lower MIN_REFS deliberately if the surface genuinely shrank.)"
  echo "check-fsi-doc-surface: FOUND $considered resolvable reference(s), expected >= $MIN_REFS (missing subject, not a pass)" >&2
  rc=1
fi

# ---- verdict ----------------------------------------------------------------------------------

if (( rc == 0 )); then
  # Green — and it SAYS WHAT IT READ, so a reader can tell "30 references, all exported" from
  # "matched nothing and shrugged".
  printf 'check-fsi-doc-surface: OK — %d doc reference(s) across %d .fsi file(s), every one exported by %s.\n' \
    "$considered" "${#fsi_files[@]}" "$(printf '%s, ' "${namespaces[@]}" | sed 's/, $//')"
else
  if (( unresolved > 0 )); then
    echo "check-fsi-doc-surface: $unresolved unresolved reference(s) out of $considered considered" >&2
  fi
fi

exit "$rc"
