#!/usr/bin/env bash
#
# Fail the PACK when FS.GG.Game.Core's packed api-surface is INCOMPLETE or does not faithfully mirror
# the compiled surface (FS.GG.Game#462).
#
# WHAT THIS GUARDS, and why it is a Game-repo problem.
#
# A scaffolded game product does not author its `docs/api-surface/**`; it VENDORS, verbatim, the
# `api-surface/` folder FS.GG.Game.Core packs into its nupkg (Directory.Build.local.props packs every
# `**/*.fsi` under the project into `api-surface/`). FS.GG.SDD#644 reported that products were
# vendoring an INCOMPLETE subset — the game-family modules a milestone builds on were systematically
# missing — and authors recovered the signatures by reflecting the shipped DLL, a ~10-minute tax per
# milestone across three products. The adjudicated decision (issue #462, 2026-07-22) put the
# completeness guarantee HERE: the packed surface must be complete and well-formed, enforced by a
# pack-time gate, so a missing module fails the RELEASE rather than surfacing downstream as a
# scaffolded-product gap. (The Templates half — vendoring the full set verbatim — is #270, not this.)
#
# THE ORACLE IS ALREADY CHECKED IN, so this needs no build and no reflection. The exported surface of
# the package lives in `readiness/surface-baselines/<pkg>.txt` (types) and
# `readiness/surface-baselines/members/<pkg>.txt` (members); both are regenerated by
# scripts/refresh-surface-baselines.fsx and held current by gate.yml's `surface-baseline-drift` job
# (#236). A top-level module or type absent from those files is absent from the package. This gate
# rides on that job's guarantee exactly as scripts/check-fsi-doc-surface.sh does: the baseline is the
# authoritative statement of what the DLL exports, and this gate asserts the PACKED `.fsi` surface
# expresses all of it.
#
# TWO CHECKS, each a distinct release-blocking failure mode:
#
#   1. COMPLETENESS (oracle -> pack). Every top-level exported root (module or type) the baseline
#      declares must be DECLARED in some packed `.fsi`. This catches the #644 shape directly: a public
#      module compiled into the DLL but shipped without a companion `.fsi` is exported by the assembly,
#      lands in the drift-gated baseline, and is SILENTLY ABSENT from the packed api-surface a product
#      vendors. Filename is NOT the subject — `Difficulty` is a top-level module that lives inside
#      Ai.fsi, so the check reads what the `.fsi` files DECLARE, never what they are named.
#
#   2. PACK FIDELITY (pack == compile). The set of `.fsi` the pack will ship must equal the set of
#      `.fsi` the project COMPILES (its `<Compile Include="…fsi">` list). The pack glob is `**/*.fsi`,
#      which is wider than the compile set: a stray or leftover `.fsi` in the project directory that is
#      NOT in the compile list is never checked by the F# compiler, yet the glob would pack it and ship
#      it to consumers as authoritative surface — a "malformed module" that no build ever validated.
#      The mirror failure — a compiled module dropped from the pack — is caught in the same comparison.
#      (A same-scope duplicate WITHIN a compiled `.fsi` — the Step/Reach triplication a downstream
#      mirror once exhibited — cannot occur in a `.fsi` the compiler accepts, so it is the compiler's
#      to reject, not this gate's; what the compiler cannot see is an UNCOMPILED packed `.fsi`, which
#      is exactly what check 2 refuses.)
#
# THE FAILURE THAT MATTERS IS NOT THIS SCRIPT GOING RED. It is this script reading NOTHING — a moved
# baseline, a re-shaped member line, a `<Compile>` list this parser no longer understands — and
# reporting that in GREEN, indistinguishable from "the surface is complete". So, exactly as
# check-fsi-doc-surface.sh and check-pin-coherence.sh do, this script asserts its SUBJECT before its
# VERDICT: an absent or empty baseline is a red, an absent `.fsi` set is a red, deriving fewer than
# MIN_ROOTS exported roots is a red, and parsing zero `.fsi` declarations or zero compiled entries is a
# red — because a completeness claim over a subject you could not read is a claim about nothing
# (FS-GG/.github#266).
#
#   usage: scripts/check-packed-api-surface.sh [baseline-dir] [fsi-dir] [fsproj] [package-namespace]
#
set -uo pipefail

BASELINE_DIR="${1:-readiness/surface-baselines}"
FSI_DIR="${2:-src/Game.Core}"
FSPROJ="${3:-src/Game.Core/FS.GG.Game.Core.fsproj}"
PKG_NS="${4:-FS.GG.Game.Core}"

# ZERO-MATCH FLOOR. FS.GG.Game.Core exports ~40 top-level roots today; a collapse toward zero means the
# baseline shape or this parser rotted, not that the surface shrank to nothing. This is the number that
# turns "I derived no roots" from a pass into a red. Lower it deliberately if the surface genuinely
# shrinks.
MIN_ROOTS="${MIN_ROOTS:-10}"

members_file="$BASELINE_DIR/members/$PKG_NS.txt"
types_file="$BASELINE_DIR/$PKG_NS.txt"

rc=0

# ---- subject: the baselines (the exported-surface ORACLE) -------------------------------------

for f in "$members_file" "$types_file"; do
  if [[ ! -f $f ]]; then
    echo "::error::check-packed-api-surface: $f not found. The surface baseline is the ORACLE for this gate — a missing oracle is a finding, not a pass. Run: dotnet fsi scripts/refresh-surface-baselines.fsx"
    echo "check-packed-api-surface: $f not found" >&2
    exit 1
  fi
  if [[ ! -s $f ]]; then
    echo "::error::check-packed-api-surface: $f is empty. An empty oracle would make every module 'not exported', so this gate would pass over a surface it never read."
    echo "check-packed-api-surface: $f is empty" >&2
    exit 1
  fi
done

# ---- subject: the packed .fsi set -------------------------------------------------------------
#
# The pack globs `$(MSBuildProjectDirectory)/**/*.fsi` excluding bin/ and obj/
# (Directory.Build.local.props, label "api-surface"), so the set of files this find yields IS the set
# of `.fsi` that ship in the nupkg's api-surface/ folder.

mapfile -t fsi_files < <(find "$FSI_DIR" -name '*.fsi' -type f \
  -not -path '*/bin/*' -not -path '*/obj/*' | sort)
if (( ${#fsi_files[@]} == 0 )); then
  echo "::error::check-packed-api-surface: no .fsi files under $FSI_DIR. The signature files are the packed SUBJECT of this gate — if they moved, this gate is reading nothing and must say so rather than pass."
  echo "check-packed-api-surface: no .fsi files under $FSI_DIR" >&2
  exit 1
fi

# ---- subject: the fsproj compile list ---------------------------------------------------------

if [[ ! -f $FSPROJ ]]; then
  echo "::error::check-packed-api-surface: $FSPROJ not found. The compile list is the second subject (check 2 compares the packed set against it); it cannot be absent and the gate green."
  echo "check-packed-api-surface: $FSPROJ not found" >&2
  exit 1
fi

roots_file=$(mktemp)
declared_file=$(mktemp)
packed_names_file=$(mktemp)
compiled_names_file=$(mktemp)
trap 'rm -f "$roots_file" "$declared_file" "$packed_names_file" "$compiled_names_file"' EXIT

# ---- derive the exported top-level roots from the oracle --------------------------------------
#
# A member line is `<fully.qualified.name><generics>(<args>) : <return>` or `<name> : <type> [get]`;
# strip everything from the first `<`, `(` or ` :`. A type line is already a bare name. Then: drop the
# `` `N `` generic-arity suffix, strip the package namespace, and keep the FIRST segment (cut at the
# first `.` for a module member or `+` for a nested type) — that first segment is the top-level root
# (module or type) the `.fsi` set must declare.
{
  sed -E 's/[<(].*//; s/ :.*//' "$members_file"
  cat "$types_file"
} \
  | sed -E 's/`[0-9]+//g' \
  | sed -E "s/^${PKG_NS//./\\.}\\.//" \
  | sed -E 's/[.+].*//' \
  | grep -E '^[A-Za-z_]' | sort -u > "$roots_file"

n_roots=$(wc -l < "$roots_file")
if (( n_roots < MIN_ROOTS )); then
  echo "::error::check-packed-api-surface: derived only $n_roots exported root(s) from $BASELINE_DIR, expected at least $MIN_ROOTS. The baseline files exist but the member/type line shape this parser expects changed — the oracle parse rotted, and this gate will NOT report that as green. (Lower MIN_ROOTS deliberately if the surface genuinely shrank.)"
  echo "check-packed-api-surface: derived $n_roots roots, expected >= $MIN_ROOTS (missing subject, not a pass)" >&2
  exit 1
fi

# ---- the packed surface's declared type/module names (top-level AND nested) -------------------
#
# Every `type X`/`module X`/`and X` declared anywhere in the packed `.fsi` set. `and` catches a type in
# a mutually-recursive group (`type Foo = … and Bar = …`), whose `Bar` is just as much a top-level root
# as `Foo`. Nested declarations (e.g. `Pathfinding.Step`, `Physics.Config`) are included too, and every
# extra name is harmless: the set is only ever COMPARED as a superset of the roots, so an extra entry
# never fails completeness — only a MISSING root does.

grep -rhoE '^[[:space:]]*(\[<[^]]*>\][[:space:]]*)?(type|module|and)[[:space:]]+[A-Za-z_][A-Za-z0-9_]*' \
  "${fsi_files[@]}" \
  | sed -E 's/.*(type|module|and)[[:space:]]+//' | sort -u > "$declared_file"

if [[ ! -s $declared_file ]]; then
  echo "::error::check-packed-api-surface: parsed 0 type/module declarations out of ${#fsi_files[@]} .fsi file(s). The files exist but nothing matched the expected \`type\`/\`module\` declaration shape — the .fsi grammar this parser reads changed. It will NOT report that as green."
  echo "check-packed-api-surface: parsed 0 declarations from the .fsi set (format drift)" >&2
  exit 1
fi

# ---- CHECK 1: COMPLETENESS — every exported root is declared in some packed .fsi --------------

missing=0
while IFS= read -r root; do
  [[ -n $root ]] || continue
  if ! grep -qxF "$root" "$declared_file"; then
    echo "::error::check-packed-api-surface: exported module/type \`$PKG_NS.$root\` has NO declaration in the packed api-surface ($FSI_DIR/**/*.fsi). The assembly exports it (it is in the surface baseline), so a scaffolded product vendoring this pack would be MISSING it — the exact FS.GG.SDD#644 gap. Add the companion \`.fsi\` that declares \`$root\` (and add it to $FSPROJ's <Compile> list). If \`$root\` should NOT be public, hide it and re-run scripts/refresh-surface-baselines.fsx."
    echo "check-packed-api-surface: INCOMPLETE — \`$root\` is exported but no packed .fsi declares it" >&2
    missing=$((missing + 1))
    rc=1
  fi
done < "$roots_file"

# ---- CHECK 2: PACK FIDELITY — the packed .fsi set equals the compiled .fsi set ----------------
#
# The packed set is `fsi_files` reduced to basenames (the project dir is flat). The compiled set is
# every `<Compile Include="…fsi">` in the fsproj, likewise as basenames.

printf '%s\n' "${fsi_files[@]}" | sed -E 's#.*/##' | sort -u > "$packed_names_file"

grep -oE 'Include="[^"]+\.fsi"' "$FSPROJ" \
  | sed -E 's/^Include="//; s/"$//; s#.*[\\/]##' | sort -u > "$compiled_names_file"

if [[ ! -s $compiled_names_file ]]; then
  echo "::error::check-packed-api-surface: parsed 0 \`<Compile Include=\"*.fsi\">\` entries from $FSPROJ. The compile list is check 2's subject — parsing none of it means this parser no longer understands the project file, not that nothing is compiled. Red rather than a vacuous green."
  echo "check-packed-api-surface: parsed 0 compiled .fsi entries from $FSPROJ (format drift)" >&2
  exit 1
fi

# packed but not compiled: a stray/leftover .fsi the compiler never checked, that the glob would ship.
while IFS= read -r name; do
  [[ -n $name ]] || continue
  echo "::error::check-packed-api-surface: \`$name\` is under $FSI_DIR and WOULD be packed into the api-surface, but is NOT in $FSPROJ's <Compile> list — so the F# compiler never validates it, yet consumers vendor it as authoritative surface. Either compile it (add it to <Compile>) or remove the stray file."
  echo "check-packed-api-surface: STRAY — packed but not compiled: $name" >&2
  rc=1
done < <(comm -23 "$packed_names_file" "$compiled_names_file")

# compiled but not packed: a module the pack drops — its surface would be missing downstream.
while IFS= read -r name; do
  [[ -n $name ]] || continue
  echo "::error::check-packed-api-surface: \`$name\` is compiled (in $FSPROJ's <Compile> list) but WOULD NOT be packed into the api-surface — its public surface would be missing from what products vendor. Restore it to the pack glob, or explain the exclusion."
  echo "check-packed-api-surface: DROPPED — compiled but not packed: $name" >&2
  rc=1
done < <(comm -13 "$packed_names_file" "$compiled_names_file")

# ---- verdict ----------------------------------------------------------------------------------

if (( rc == 0 )); then
  printf 'check-packed-api-surface: OK — %d exported root(s) of %s all declared across %d packed .fsi file(s), and the packed set matches the %d-entry compile list.\n' \
    "$n_roots" "$PKG_NS" "${#fsi_files[@]}" "$(wc -l < "$compiled_names_file")"
else
  echo "check-packed-api-surface: FAILED — $missing missing module(s); see errors above" >&2
fi

exit "$rc"
