#!/usr/bin/env python3
"""Generate the one shared F# fixture vector from the authored M4 JSON corpus."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tests/Game.Core.Fable.Tests/fixtures/v1/cases.json"
TARGET = ROOT / "tests/Game.Core.Fable.Tests/shared/GeneratedCases.fs"


def integer(value: int) -> str:
    if value == -2147483648:
        return "System.Int32.MinValue"
    if value == 2147483647:
        return "System.Int32.MaxValue"
    return str(value)


def cell(value: list[int]) -> str:
    return f"cell {integer(value[0])} {integer(value[1])}"


def cells(values: list[list[int]]) -> str:
    return "[ " + "; ".join(cell(value) for value in values) + " ]"


def render_case(case: dict[str, object]) -> str:
    case_id = case["id"]
    operation = case["operation"]

    if operation == "Cell.order":
        return f"CellOrder ({case_id}, {cells(case['cells'])})"
    if operation == "Edges.edgeBetween":
        return f"EdgeBetween ({case_id}, {cell(case['a'])}, {cell(case['b'])})"
    if operation == "Los.lineOfSightBy":
        return (
            f"LineOfSight ({case_id}, {case['mode']}, {cell(case['a'])}, "
            f"{cell(case['b'])}, {cells(case['blocked'])})"
        )
    if operation == "Pathfinding.astar":
        bounds = ", ".join(integer(value) for value in case["bounds"])
        return (
            f"Astar ({case_id}, {case['neighbourhood']}, {case['maxVisited']}, "
            f"{cell(case['start'])}, {cell(case['goal'])}, ({bounds}), "
            f"{cells(case['blocked'])})"
        )
    raise ValueError(f"unsupported operation {operation!r}")


def render(document: dict[str, object]) -> str:
    if document.get("schemaVersion") != 1:
        raise ValueError("cases.json must use schemaVersion 1")

    cases = document.get("cases")
    if not isinstance(cases, list) or not cases:
        raise ValueError("cases.json must contain a non-empty cases array")

    ids = [case["id"] for case in cases]
    if len(ids) != len(set(ids)) or ids != sorted(ids):
        raise ValueError("fixture ids must be unique and ascending")

    rendered = "\n          ".join(render_case(case) for case in cases)
    return f"""// Generated by scripts/generate-fable-lockstep-cases.py from fixtures/v1/cases.json.
// Do not edit this file directly.
namespace FS.GG.Game.Core.LockstepFixtures

open FS.GG.Game.Core

type Fixture =
    | CellOrder of caseId: int * cells: Cell list
    | EdgeBetween of caseId: int * a: Cell * b: Cell
    | LineOfSight of caseId: int * mode: LineMode * a: Cell * b: Cell * blocked: Cell list
    | Astar of
        caseId: int *
        neighbourhood: Neighbourhood *
        maxVisited: int *
        start: Cell *
        goal: Cell *
        bounds: (int * int * int * int) *
        blocked: Cell list

[<RequireQualifiedAccess>]
module GeneratedCases =

    let private cell col row : Cell = {{ Col = col; Row = row }}

    let all : Fixture list =
        [ {rendered} ]
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    output = render(json.loads(SOURCE.read_text(encoding="utf-8")))
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != output:
            print(f"{TARGET.relative_to(ROOT)} is stale; run {Path(__file__).name}")
            return 1
        print("fable lockstep generated cases: current")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(output, encoding="utf-8")
    print(f"generated {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
