<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ContractTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Wasm.Contracts/FS.GG.Wasm.Contracts.fsproj" />
    <PackageReference Include="Expecto" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="YoloDev.Expecto.TestSdk" />
  </ItemGroup>
</Project>
